### ISSUE TITLE
editor.action.triggerSuggest failed.

### ISSUE THREAD

**Issue by Jax0rz** [sublimelsp/LSP-html#23]
![CleanShot 2020-11-29 at 00 12 59@2x](https://user-images.githubusercontent.com/7557357/100520226-ad4a7600-31d7-11eb-94e0-138a2d0ca5d3.png)

**Comment by rchl** [comment]
`on_pre_server_command` doesn't seem sufficient for handling this case as it doesn't provide the `View`. I'm not considering getting the active one as a viable solution.

**Comment by rchl** [comment]
I mean, technically getting the active view should work but I'm allergic to such solutions.

**Comment by rwols** [comment]
I agree, but for the purposes of getting things to work, I think it's fine. I use it here for instance: https://github.com/sublimelsp/LSP-SonarLint/blob/master/plugin.py#L85

**Comment by rchl** [comment]
We could add pass the View, if relevant. We could even stuff it into the `command` dict to avoid breaking changes.

**Comment by rwols** [comment]
I’m fine with a breaking change.
