### ISSUE TITLE
Basic support for embedded JavaScript?

### ISSUE THREAD

**Issue by john-cj** [sublimelsp/LSP-html#27]
Here is a simple file:

```html
<p>some text</p>

<script>
  const foo = 'aaa';
  console.log(foo);
</script>
```

When I try to use LSP to rename `foo` to `bar` (I have both LSP-typescript and LSP-html installed), the name doesn't change and instead I see the following message in the status bar:

> No rename edits returned

Is this by intent or just an error? Do I need some special settings enabled?

Things like renaming `<p>` to `<div>` in HTML files or the `foo` constant to `bar` in JavaScript files works fine. The described issue is only happens when JS is inside HTML.

Cheers.

**Comment by jfcherng** [comment]
`LSP-typescript` is not activated in HTML file after all... and I don't think you want to activate it after my trying. It just marks everything illegal since it's a HTML file.

**Comment by john-cj** [comment]
So in other words this feature doesn't really work, right?

(English is a foreign language for me. I feel that the sentence above might be considered aggressive, but actually I don't mean anything like this.)

Before asking there, I already checked issues listed on LSP-typescript repository and found this one: https://github.com/sublimelsp/LSP-typescript/issues/18 As follows from that discussion, this feature seems work (the guy who asked for it seems to be happy after all...). But I might wrong, of course.

**Comment by jfcherng** [comment]
He's asking about autocompletion while your cases is renaming.

In short, I don't think `LSP-typescript` has something to do here. `LSP-html` seems to be able to recognize the token `foo` so it may be able to do a renaming theoretically but obviously it doesn't. So, I would probably recommend opening a feature request in VSCode's repo since the server is a part of VSCode.

---

Or, maybe it works in VSCode? I didn't try but if it works in VSCode, maybe there is something else that we have to configure.

**Comment by john-cj** [comment]
Aha, thanks. I will check it and open an issue there if necessary.

A side question. I see your screenshot is somewhat different from what I have myself. If I hover a mouse over `<p>`, I see this:

![image](https://user-images.githubusercontent.com/18004961/111802279-dace4300-88de-11eb-84d2-a055fa22d98e.png)

However, if I open a mouse over `foo`, I see this:

![image](https://user-images.githubusercontent.com/18004961/111802336-eae62280-88de-11eb-9f4c-1de5e8c08c75.png)

Or your image is from VS Code?

**Comment by jfcherng** [comment]
> Aha, thanks. I will check it and open an issue there if necessary.

Wait. It looks like the latest server is working on my side. I will make a PR later.

**Comment by jfcherng** [comment]
So after that PR, it looks like
![image](https://user-images.githubusercontent.com/6594915/111809707-3c5ad580-8910-11eb-843a-e4c5140998a1.png)
and renaming JS variable works. 🎆

**Comment by jfcherng** [comment]
> A side question. I see that your screenshot is somewhat different from what I have myself. If I hover a mouse over `<p>`, I see this:
> ...
> However, if I open a mouse over `foo`, I see this:
> ...
> Or your image is from VS Code?

Do you mean ![image](https://user-images.githubusercontent.com/6594915/111809888-6a401a00-8910-11eb-949b-cdeb6e154e7a.png)?

I didn't do anything to that, LSP in ST4 looks just like that.

**Comment by john-cj** [comment]
Yes, this is what I mean.  I don't these "Definition", "References", "Rename" options. The context menu works, but renaming still fails. 

I suppose this is probably I use ST3 and not SP4. Or maybe I need to update a package, but since ST doesn't see any updates for any packages, I simply reinstalled LSP-html. There are no changes after the reinstall, though.

**Comment by jfcherng** [comment]
> Yes, this is what I mean. I don't these "Definition", "References", "Rename" options. The context menu works, but renaming still fails.

If you are on ST 3, https://github.com/sublimelsp/LSP-html/issues/27#issuecomment-802976425 should do the job.

**Comment by john-cj** [comment]
The pop-up is now in place. I suppose that after your pull request will be accepted, the renaming will work :)

**Comment by jfcherng** [comment]
The `v1.2.0` release should fix this.
