### ISSUE TITLE
LSP-html exited with status code 1

### ISSUE THREAD

**Issue by thep0y** [sublimelsp/LSP-html#33]
![截图_sublime_text_20210901200607](https://user-images.githubusercontent.com/51874567/131668459-20310bd1-43f5-4a3c-babd-e732f437290f.png)

**Comment by jfcherng** [comment]
https://github.com/sublimelsp/LSP-html#faqs

**Comment by jfcherng** [comment]
There is a PR which should fixes this. https://github.com/sublimelsp/lsp_utils/pull/79
