### ISSUE TITLE
Wrong suggestion showed after following same steps from `lsp-css` to remove duplicate suggestions

### ISSUE THREAD

**Issue by lzaaldian** [sublimelsp/LSP-html#36]
### About the issue

Hi, I tried to use the same steps from `lsp-css` FAQ to remove duplicate suggestions but turned out removing suggestions from `lsp-html`.

### Reality

Before I use `"disable_default_completions": true`

<img width="732" alt="Jepretan Layar 2021-12-21 pukul 9 08 00 PM" src="https://user-images.githubusercontent.com/3760093/146945450-b2356ad1-7a51-455d-8c7f-085d102e1c4d.png">

After use `"disable_default_completions": true`

<img width="1440" alt="Jepretan Layar 2021-12-21 pukul 9 14 41 PM" src="https://user-images.githubusercontent.com/3760093/146946108-a2fb17be-3a27-4fb9-a01f-25f74093e629.png">

### Expected

<img width="733" alt="Jepretan Layar 2021-12-21 pukul 9 25 02 PM" src="https://user-images.githubusercontent.com/3760093/146946171-83a287fa-ccb9-4732-b059-5e553c7a9282.png">

---

Any help to show the expected result is greatly appreciated.

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/146948305-9eaf312c-7066-483b-89ca-c6082fe0bd08.png)
This is ST's built-in btw. https://github.com/sublimehq/Packages/blob/c9ef2da02b433c3d0c1ec65b109300c8bb69c359/HTML/html_completions.py#L146

**Comment by lzaaldian** [comment]
> ![image](https://user-images.githubusercontent.com/6594915/146948999-bb6bfc66-2a60-4e74-a601-3479c5470195.png)
> 
> The fact is reversed. Green is from LSP-html and orange is from [ST built-in](https://github.com/sublimehq/Packages/blob/c9ef2da02b433c3d0c1ec65b109300c8bb69c359/HTML/html_completions.py#L146). And `"disable_default_completions": true` [disables](https://github.com/sublimehq/Packages/blob/c9ef2da02b433c3d0c1ec65b109300c8bb69c359/HTML/html_completions.py#L452-L456) the ST built-in so I don't see a problem. At the same time, I can't figure out a clean solution to remove those "green" autocompletions.

Hmm.. maybe you can try what I have tried:

1. Install `lsp-html`.
2. Create a HTML file like `test.html` above or open your own HTML file.
3. Write any tag and try to press `enter` or `tab` on both suggestions (built-in and by lsp-html or green and orange like in my screenshot). Which one do you think is from `lsp-html`?

**Comment by jfcherng** [comment]
`p` is from LSP-html, `t` is from ST built-in.

**Comment by lzaaldian** [comment]
Ah.. I understand now. The `lsp-html` adds suggestions like expand tag by pressing tab when selecting the orange suggestion.

Thank you for your explanation.
