### ISSUE TITLE
html.customData not working 

### ISSUE THREAD

**Issue by blackjyn** [sublimelsp/LSP-html#37]
I just curious on the` html.customData` settings so I get play with it. 
I tried to just copy the custom data from https://github.com/octref/vscode-mavo/data/mavo.json

then save it as `custom-data.html-data.json`

### on the LSP HTML settings:

```
{
	"settings": {
		"html.customData": [
			"./custom-data.html-data.json"
		],	
	},
}
```

### project directory 

![html customData](https://user-images.githubusercontent.com/6046191/198829318-33bfabaa-335d-4c01-808c-d53a06c02e18.png)

### test

![html customData-test-err](https://user-images.githubusercontent.com/6046191/198829388-a1c31b7a-c0e9-4615-9cdb-3cd518231295.png)

Help?

**Comment by predragnikolic** [comment]
Hello.
`html.customData` seems to not be working.

The link that you posted above https://github.com/octref/vscode-mavo/data/mavo.json is also not working
but anyone could paste the code from:
https://code.visualstudio.com/blogs/2020/02/24/custom-data-format#_using-custom-data-format

**Comment by blackjyn** [comment]
Thanks guys! it works now! 
@predragnikolic ah yes the json custom data from https://github.com/octref/vscode-mavo/data/mavo.json is indeed not working.
I changed the `globalAttributes` to `tags` and create some more tests. 

it works flawlessly! Thank you guys!

![html customData-worked](https://user-images.githubusercontent.com/6046191/198872324-42bec39f-adff-4754-bd3e-ae89a33ba99c.png)

**Comment by blackjyn** [comment]
2 years later, this issue arises again.

Now I'm using SAP UI 5 https://sap.github.io/ui5-webcomponents/. 

To get the autocompletion it should reference the ones in the node_modules. It should be like this but not working: 

```json
{
   "settings": {
      "html.customData": [
         "./node_modules/@ui5/webcomponents/dist/vscode.html-custom-data.json",
         "./node_modules/@ui5/webcomponents-fiori/dist/vscode.html-custom-data.json"
      ]
   },
}
```

**Comment by rchl** [comment]
Feel free to provide a github repo that reproduces the issue.

**Comment by blackjyn** [comment]
@rchl the issue is custom HTML data not working (again)

**Comment by jfcherng** [comment]
Should've been fixed by https://github.com/sublimelsp/LSP-html/pull/48

**Comment by blackjyn** [comment]
thanks @jfcherng !!! 
Works again like a charm 
![image](https://github.com/user-attachments/assets/404a552d-0c5d-4249-8f86-6afc911f5d3c)

![Screenshot 2024-10-28 203457](https://github.com/user-attachments/assets/0d562707-3d3a-4cdd-98b1-9bf08a0653c7)

![image](https://github.com/user-attachments/assets/20896a9e-26b7-44bf-8931-7b2668b6a7a6)
