### ISSUE TITLE
Any way to use the JS support inside standalone JS files?

### ISSUE THREAD

**Issue by todordvv** [sublimelsp/LSP-html#40]
Hi, I love how this plugin works inside JS code between SCRIPT tags, it even has jQuery support.

Any way to configure it to work inside standalone JS files? I've only managed it to load for JS files by adding source.js to the "selector" setting in the config file, but it doesn't do anything.

I am a noob at this so sorry if I'm asking the wrong questions.
Thanks in advance.

**Comment by jfcherng** [comment]
https://packagecontrol.io/packages/LSP-typescript is for that.

**Comment by todordvv** [comment]
> https://packagecontrol.io/packages/LSP-typescript is for standalone JS/TS.

Thanks for the reply. I do have LSP-typescript installed and it's working fine for JS but it doesn't have jQuery autocomplete and I've been banging my head for two days now to find how to include it with no luck. We mostly support clients via FTP and so we don't have all the files downloaded in project folders to include stuff from so I need something like a global JS/jQuery support.

I tried ESLINT too (with a lot of reading and work just to get it to a working configuration) but that one just formats and highlights errors - no autocomplete support whatsoever.

I love how this LSP-html handles the JS stuff so I thought if possible I'd rather use it inside JS files too...

**Comment by jfcherng** [comment]
I thought that [LSP-typescript](https://packagecontrol.io/packages/LSP-typescript) should have some settings for extra include paths but I don't find them.

>  I've only managed it to load for JS files by adding source.js to the "selector" setting in the config file, but it doesn't do anything.

This server will parse the JS file as HTML then, so everything is plain text from it's point of view.

**Comment by todordvv** [comment]
> I thought that [LSP-typescript](https://packagecontrol.io/packages/LSP-typescript) should have some settings for extra include paths but I don't find them.

Yeah, thought so too and I really really tried to find a workaround to no avail...



> This server will parse the JS file as HTML then, so everything is plain text from it's point of view.

I see, so it is dependent on the server to that degree. That explains a lot thank you! I guess it's not possible (unless the client code is updated with JS support to maybe wrap the code in <script> tags and then send it, and then when received back remove the tags or something)...

**Comment by jfcherng** [comment]
Can you provide a short code snippet for testing?

**Comment by todordvv** [comment]
`document.getElementById('tarzan');

function fname() {

}


(function ($) {
	var lero = $;
})(jQuery)`

Yeah, this is the simple 5 line file I've been using today.

**Comment by todordvv** [comment]
With LSP-typescript I get autocomplete for document and window and such:

![image](https://user-images.githubusercontent.com/125922567/221091471-14824ccd-423e-4687-a0a4-e380a5959b99.png)

But none for jQuery:

![image](https://user-images.githubusercontent.com/125922567/221091516-7922c144-cf70-4b73-910f-e62cfbc3906f.png)

But in an HTML/PHP file with JS code in script tag LSP-html supports it:

![image](https://user-images.githubusercontent.com/125922567/221091662-fc14e59e-646f-4c72-9fcd-2308a1c12ee9.png)

Even the $ variable:

![image](https://user-images.githubusercontent.com/125922567/221091705-480dd757-5e16-46a9-a444-aecf8d4ba947.png)

**Comment by jfcherng** [comment]
OK. So I find how to make it work. You just need to do `npm install --dev @types/jquery` for your project.

![image](https://user-images.githubusercontent.com/6594915/221097690-c3ed5eb1-76fe-42fe-92b3-1789de82301c.png)

**Comment by todordvv** [comment]
> OK. So I find how to make it work. You just need to do `npm install --dev @types/jquery` for your project.
> 
> ![image](https://user-images.githubusercontent.com/6594915/221097690-c3ed5eb1-76fe-42fe-92b3-1789de82301c.png)
> 
> Or maybe `@types/jquery` can be installed globally. But I am not sure whether a global one can be found by the server.

Thank you so much! This is definitely a lead! Will try to install it globally somehow and see if it works. As I said no projects being loaded so I need a global solution.

Did you enable LSP-html for JS files for the screenshot?

**Comment by jfcherng** [comment]
> Did you enable LSP-html for JS files for the screenshot?

No. As I said, let LSP-html to parse JS files as HTML files is meaningless. I just enable LSP-typescript and install @type/jquery.

**Comment by jfcherng** [comment]
LSP-typescript won't work for a single file iirc.

**Comment by jfcherng** [comment]
Yes, I tried a global installation won't work. I still have another hacky solution in mind. Will post the result after some tests.

**Comment by jfcherng** [comment]
You can add 
```js
const jQuery = require('jQuery');
```
to include jQuery and tsserver will auto download `@types/jquery` to where it should globally be. But without that line, the server doesn't know that `jQuery` variable is from `jQuery` lib.

**Comment by todordvv** [comment]
> You can add
> 
> ```js
> require('jQuery');
> ```
> 
> to your code to include jQuery and tsserver will auto download `@types/jquery` to where it should globally be. But without that line, the server doesn't know that `jQuery` variable is from `jQuery` lib.

Man, you're a rock star! that require line makes LSP-typescript work!

I can live with that addition to files should jQuery be needed. And I presume this ties into the global installation of npm jquery and @types/jquery - and without that it's not gonna work? (asking this last bit because I'm trying to learn/understand).

In any case this definitely is HUGE help thank you so so much!

**Comment by jfcherng** [comment]
I am not sure how exactly the server works but you can "Go to Definition" to jQuery to see where `@types/jQuery` is installed. I think the possible next step for you is in another issue that you created on LSP-typescript's repository: to require jQuery automatically. I guess that's what LSP-html's server does probably in memory.

**Comment by predragnikolic** [comment]
It looks like the HTML language server gives auto complete suggestions for jQuery, (it provides jQuery autocomplete even in project that do not use jQuery :), which is "bad", I do not see this as an issue, but if I did, I would still consider that a server issue)

> Yes, I tried a global installation won't work. I

It wont work globally, this is by typescript design. See this https://github.com/sublimelsp/LSP-typescript/issues/200#issuecomment-1445187841

I needed some time to read this thread, I think all questions were answered, in one way or another, so I will close this.

If you run into additional issues, feel free to open a new issue.
Or if there are still some things unresolved here, feel free to reopen.
