### ISSUE TITLE
Show deprecated?

### ISSUE THREAD

**Issue by interpreterK** [sublimelsp/LSP-html#41]
I'm not sure if this is a missing feature not implemented yet by sublime-LSP or LSP-html or that its a VSCode only thing, but maybe its off by default? Or.. color scheme is missing a rule to mark it? Missing package..? I was not able to find anything related to showing deprecated in the lsp-HTML settings for Sublime Text 4.

## Sublime (LSP, LSP-html):
![Screenshot_20230321_172159](https://user-images.githubusercontent.com/80614657/226743743-b3235667-1c7f-4373-8b21-84e7d016b4cd.png)
![Screenshot_20230321_172738](https://user-images.githubusercontent.com/80614657/226745061-f1339162-0a69-4159-b895-d2b6a17a3b84.png)

## VSCode:
![Screenshot_20230321_172937](https://user-images.githubusercontent.com/80614657/226745455-ca075531-1b9a-4c41-a637-c3af51574f59.png)
![Screenshot_20230321_172957](https://user-images.githubusercontent.com/80614657/226745508-78d0dc4f-3281-47b8-ba37-8e69aa2e00bd.png)

### LSP-html is running and working:
![Screenshot_20230321_172820](https://user-images.githubusercontent.com/80614657/226745191-dfcffedf-38b3-4107-873a-c8fe1f382ea0.png)
![Screenshot_20230321_172854](https://user-images.githubusercontent.com/80614657/226745298-af9b708d-d2eb-4397-b648-3f2cf40f7766.png)

**Comment by jfcherng** [comment]
What do you mean? The `border` attr?

**Comment by jfcherng** [comment]
It's not provided by the HTML language server.
You can search `invalid.deprecated.html` in VSCode's HTML syntax definition: https://github.com/microsoft/vscode/blob/831a131f27f103b433bbff94726876039f8b55c9/extensions/html/syntaxes/html.tmLanguage.json#L2337-L2348

**Comment by interpreterK** [comment]
Oh. My mistake then, didn't know it was hard coded into VSCode like that... would have made sense if they indicated deprecated items in base LSP.
