### ISSUE TITLE
adding HTML (Liquid) syntax extension support to html files

### ISSUE THREAD

**Issue by hozza** [sublimelsp/LSP-html#44]
Essentially [this plugin adds the Liquid template language to ST4](https://github.com/SublimeText/Liquid), but now LSP-html will not run on the HTML in these files.

Is it possible to run LSP-html Diagnostics on the HTML around the Liquid markup or would it throw too many errors?

**Comment by jfcherng** [comment]
You can edit https://github.com/sublimelsp/LSP-html/blob/cd7f4fa0823d1a90cdbc1c7aac91dba95407e33c/LSP-html.sublime-settings#L145-L146 to make it run on any Syntax.

**Comment by rchl** [comment]
Note that it most likely won't understand the "liquid" specific content but there is nothing we can do about it.

You'd most likely need to look for liquid-specific language server which might not exist.

**Comment by hozza** [comment]
Excellent thanks. I'll give that a go.

I've not found a specific liquid LSP yet, I'll see if this will work.

**Comment by predragnikolic** [comment]
Isn't this the language server for liquid?
https://github.com/Shopify/theme-check

**Comment by hozza** [comment]
> or even more aggressive
> 
> ```
>  "selector": "text.html | embedding.php", 
> ```

Thanks! :partying_face: I eventually got this working for my use-case, although I had some trouble so I'll detail here in case someone comes searching for the same thing.

Essentially I'm using Jekyll and need HTML (Liquid) syntax highlighting on `.html` file extensions only within Jekyll projects. I didn't want to set HTML (Liquid) as my default syntax for all HTML file extensions globally either, so I was using the ["Project Specific Syntax Settings"](https://packagecontrol.io/packages/Project%20Specific%20Syntax%20Settings) plugin which allows me to override the syntax for HTML file extensions to HTML (Liquid) on a per-project basis via the `project_name.sublime-settings` file.

Essentially, this plugin does not set the syntax properly and so even the aggressive selector approach suggested would not work _sometimes_. After much troubleshooting, it seems that it does work when the HTML (Liquid) syntax is manually set. Digging further [I found issue #20](https://github.com/reywood/sublime-project-specific-syntax/issues/20) on the almost abandoned plugin about a similar issue, I switch to the [ApplySyntax plugin](https://packagecontrol.io/packages/ApplySyntax) which does apply syntax properly and so the the selector approach above now works.

Configs for getting jekyll working with liquid syntax and HTML and cSpelling LSP.

`.sublime-project` for the Apply Syntax config.
```jsonc
{
  "folders": [
    {
      "path": "/path/to/jekyll/site"
    }
  ],
  "settings": {
    "project_syntaxes": [
      {
        "syntax": "Liquid/Syntaxes/HTML (Liquid)",
        "extensions": [
          "html"
        ]
      }
    ]
  }
}
```

`LSP-html.sublime-settings`:
```jsonc
// added `text.html` for "liquid" HTML templating files
// LINK https://github.com/sublimelsp/LSP-html/issues/44#issuecomment-1792406662
{
	"selector": "text.html | embedding.php", 
}
```

I also used this selector change for cSpelling! `LSP-cspell.sublime-settings`:
```jsonc
  ...
  // I dont't think you can append to the defaults, so I added `text.html` to the end of default string for "liquid" HTML templating files
  // LINK https://github.com/sublimelsp/LSP-html/issues/44#issuecomment-1792406662
	"selector": "source.dosbatch | source.c | source.c++ | source.objc | source.objc++ | source.clojure | source.cs | source.cake | source.css | source.dart | source.diff | source.dockerfile | source.elixir | source.erlang | source.fsharp | text.git-commit | source.go | source.gomod | source.graphql | source.haskell | text.html.basic | source.ini | source.java | source.jsx | source.js.react | source.js | source.tsx | source.ts | source.json | source.julia | text.tex.latex | source.less | source.lua | source.makefile | text.html.markdown | source.perl | text.html.twig | text.blade | embedding.php | text.plain | source.powershell | source.python | source.r | source.ruby | source.rust | source.scala | source.scss | source.sql | source.swift | text.html.vue | text.xml | text.html.svelte | source.yml | source.yaml | text.html"
}
```

**Comment by jfcherng** [comment]
> I also used this selector change for cSpelling! LSP-cspell.sublime-settings:

If you mean to use it for everything, just `source, text`.
