### ISSUE TITLE
Don't start LSP-html in php

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP-html#9]
I propose to not start LSP-html in php files.
I opened a php file, and triggered the AC. That fired a completion request to the LSP-html server, instead to the LSP-intelephense server. 

Ideally we should have a Promise.all or asyncio.gather to fire completion request to all servers, and combine the results, but I would stick with simplicity for now and just remove the php scope.

Any thoughts on this?

**Comment by rchl** [comment]
I'm fine with that but I don't do much in PHP...

But at least for ST4 we might be able to tweak settings so that they cooperate better. Maybe.

**Comment by jfcherng** [comment]
I have the following in my `LSP-html.sublime-settings`.

```js
{
    "languages": [
        {
            "languageId": "html",
            "document_selector": "text.html.basic | embedding.php",
            "feature_selector": "text.html",
        },
    ],
}
```

**Comment by rchl** [comment]
Hmm, looks like currently both LSP-html and LSP-intelephense are not started in PHP in ST4 due to my breaking change https://github.com/sublimelsp/lsp_utils/commit/6ab09ed57eeb120e2260b712b168263c3083ebc3 . Gotta sort it out (and also try to handle this one).

**Comment by rchl** [comment]
I've created #15 to make it initialize in PHP and have less priority than intelephense in HTML blocks.
So the fix will address the original issue without disabling it for PHP files.
